### ISSUE TITLE
QLabel has been deleted

### ISSUE THREAD

**Issue by BorFour** [BorFour/process_launcher#10]
The following error happens when trying to run a process. It is fixed by entering the edit mode and going back to the launch mode

``Traceback (most recent call last):
  File "/home/borja/github/process_launcher/process_group_widget.py", line 229, in run_all
    process_widget.process.restart()  # REVIEW: or run?
  File "/home/borja/github/process_launcher/process.py", line 43, in restart
    self.run()
  File "/home/borja/github/process_launcher/process.py", line 85, in run
    '--workdir', self.directory,
  File "/home/borja/github/process_launcher/process.py", line 38, in directory
    return self.directory_widget.text()
RuntimeError: wrapped C/C++ object of type QLabel has been deleted
``

**Comment by BorFour** [comment]
Fixed this bug in https://github.com/BorFour/process_launcher/commit/07f3473d9c9898bdcbb3b1a8387a2564fae919f3
